AWSTemplateFormatVersion: '2010-09-09'
Description: Provision an S3 bucket with versioning enabled and an EC2 instance with read access to the bucket.

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    Description: EC2 instance type

  BucketName:
    Type: String
    Description: Name of the S3 bucket

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-0c55b159cbfafe1f0
      SecurityGroupIds:
        - !GetAtt MySecurityGroup.GroupId
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y aws-cli
          aws s3 cp s3://${BucketName}/example.txt /home/ec2-user/example.txt

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow inbound SSH and S3 access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

Outputs:
  InstancePublicIp:
    Description: Public IP address of the EC2 instance
    Value: !GetAtt MyEC2Instance.PublicIp

  BucketNameOutput:
    Description: Name of the created S3 bucket
    Value: !Ref MyS3Bucket
